#+TITLE: Cover Letter
#+OPTIONS: toc:nil

\noindent
Dear KAUST recruiting team,
\indent

I am writing to express my interest in the postdoctoral position in Optimization and Machine Learning Lab at KAUST. I believe that my strong background in machine learning, combined with my passion for research, make me an excellent fit for this position.

As a recent PhD graduate in Electrical Engineering, I have gained extensive experience in machine learning through my research and coursework. I have published several papers on machine learning topics, including “Ensemble Optimization for Invasive Ductal Carcinoma
(IDC) Classification Using Differential Cartesian Genetic Programming,” in IEEE Access which is a Q1 journal, “Ensemble Optimization Using Clonal Selection Algorithm
for Breast Cancer Histology Image Classification”, “Adaptive PSO-Based Ensemble Optimization for Histology Image Classification”, and “Genetically Optimized Heterogeneous Ensemble for Histological Image Classification”. In addition, I have completed coursework in advanced machine learning techniques and biologically inspired computing and have completed a number of independent and course-related projects applying machine learning to real-world problems.

In my previous position as a PhD candidate at the University of Toledo, I have gained valuable experience working on a team of researchers to develop and implement machine learning algorithms for histology image classification. I have also had the opportunity to mentor new grad colleagues, in machine learning, which has further developed my ability to effectively communicate technical concepts to a wide range of audiences.

I am excited about the opportunity to contribute to the research being conducted at KAUST and believe that my skills and experience make me a strong candidate for this postdoctoral position. Thank you for considering my application. I look forward to the opportunity to discuss my qualifications in more detail.

\noindent
Sincerely,\\
Eid Alkhaldi
