#+LATEX_CLASS: lukecv
#+LATEX_HEADER: \input{/home/alkhaldieid/repos/cv/org/cvheader.tex}
#+LATEX_CLASS_OPTIONS: [letterpaper,10pt]


#+LATEX: \maketitle
* Basic Info

\begin{minipage}[t]{.5\linewidth}
\begin{tabular}{rp{.75\linewidth}}
	\baselineskip=20pt
	\email{} :	& \href{mailto:eid.alkhaldi@gmail.com}{eid.alkhaldi@gmail.com}\\
	\yt{} : & \href{https://www.linkedin.com/in/eid-alkhaldi-38a10212a/}{https://www.linkedin.com/in/eid-alkhaldi-38a10212a/}
\end{tabular}
\end{minipage}
\begin{minipage}[t]{.5\linewidth}
\begin{tabular}{rl}
	\gh{} : & \href{http://github.com/alkhaldieid}{github.com/alkhaldieid}\\

\end{tabular}
\end{minipage}

\begin{itemize}
\item  An Electrical Engineering PhD candidate at the \href{https://www.utoledo.edu/engineering/electrical-engineering-computer-science/}{University of Toledo \www}, focusing mostly on the diagnostic applications of Deep Learning in medical imaging.

\end{itemize}

# %\item Maintainer and developer of a Deep Learning-based Cancer Classification system at \href{https://github.com/alkhaldieid/iciar}{https://github.com/alkhaldieid/iciar \www}
# %\end{itemize}

* Institutions

\entry{2017--present}
	{Ph.D. in Engineering}
	{\ut, Toledo, Ohio, USA}
	{
	Focusing on medical image processing, Artificial Inteligence and Deep Learning. Advisor: \ezz.
	}

\entry{2015--2017}
	{M.S. in Electrical Engineering}
	{\ut, Toledo, Ohio, USA}

\entry{2014}
	{B.S. in Electrical Engineering}
	{\osu, College of Engineering, Architecture and Technology}
	{
	Stillwater, Oklahoma, USA
	}

\section{Publications}


  \entry{In Progress}
	{Ensemble Optimization for Histological Image Classification}
	{Dissertation, \ut}
	{
    Committee: \ezz, \secondmember, \thirdmember, \fourthmember.
	}

  \entry{In Progress}
  {Ensmble Optimization for IDC Classification Using CSA}
  {}

  \entry{2022 Submitted}
  {Ensmble Optimization for IDC Classification Using dCGPANN}
  {}

  \entry{2019}
	{Alkhaldi, E. & Salari, E. Genetically Optimized Heterogeneous Ensemble for Histological Image Classification.}
	{\small{International Journal of Science and Engineering Investigations
      (IJSEI), 8(95), 113-118.}
    \href{http://www.ijsei.com/papers/ijsei-89519-16.pdf}{\pdf} {http://www.ijsei.com/papers/ijsei-89519-16.pdf}}

  \entry{2021}
	{Alkhaldi, E. & Salari, E. Adaptive PSO-Based Ensemble Optimization for Histology Image Classification.}
	{\small{International Journal of Computer Science and Technology
      (IJCST), Vol 12, Issue 1, Version Jan-March 2021.}
    \href{https://www.ijcst.com/vol12/issue1/3-eid-alkhaldi.pdf}{\pdf} {https://www.ijcst.com/vol12/issue1/3-eid-alkhaldi.pdf}}

* Presentations

\entry{Soon}
	{``Ensemble Optimization for Histological Image Classification''}
	{PhD Proposal Defense}

* Licenses & Certifications
\entry{2018}
{Improving Deep Neural Networks: Hyperparameter Tuning, Regularization And Optimization
  \href{https://www.coursera.org/account/accomplishments/verify/SYMNEXXAAUM8}{\www}}
{Coursera, issued March 2018}

\entry{2018}
{Neural Networks and Deep Learning
  \href{https://www.coursera.org/account/accomplishments/verify/QVDGURZQCDDZ}{\www}}
{Coursera, issued February 2018}

* Languages

\entry{Human}
	{Arabic, English}
	{}
	{}

\entry{Machine}
	{Python, Matlab/GNU Octave, bash/shell, C, C++ , markup languages including {\LaTeX} / {\XeTeX}, R Markdown, basic HTML.}
	{}
	{}
\entry{Deep Learning}
	{PyTorch, TensorFlow, Keras, Fastai and Sikit-Learn}
	{}
	{}
\entry{Other Tools}
	{OpenCV, MATLAB, DEAP (Genetic optimization framamework) , Linux }
	{}
	{}

* Research Interests

\begin{itemize}
\item Digital Image Processing, Signal Processing and Communication Systems
\item Applications of Artificial Intelligence in Medical images, healthcare systems, Cybersecurity and Finance
\item Machine Learning, Deep Learning, Data Science and Big Data
\item Hyperparameter Tuning, Non-convex Optimiation, Numerical Methods and Biologically Inspired Computing

\end{itemize}
* Public Code and Scripts

\entry{In Progress}
	{Genetic Algorithm Ensemble Optimization \href{https://github.com/alkhaldieid/gae}{\gh}}
	{A Genetic Algorithm based optimization framework that automatically tune ensembles hyperparameters}

\entry{In Progress}
	{Quantim Computing based Transfer Learning \href{https://github.com/alkhaldieid/gpe}{\gh}}
	{A Quantum based Learning Rate Scheduler for transfer learning models}

\entry{In Progess}
	{Histology Image Classification models for ICIAR \href{https://github.com/alkhaldieid/iciar}{\gh}}
	{Various pretrained models for breast cancer detection in histology images. Achieved 88\% accuracy on the ICIAR  \href{https://github.com/alkhaldieid/iciar}{\www}  dataset }
	{}




* Engineering Projects

\begin{itemize}
	\item UC Davis NATCAR Design Contest (Oklahoma State University 2014 team).
	\begin{itemize}
		\item Responsibilities: \dots{}
			\begin{itemize}
				\item Microprocessor and interface with other blocks of the system
				\item Design the power circuit for the whole system
				\item Choosing the best value Battery that meet the project specs
				\item The servo control software
			\end{itemize}
	\end{itemize}
\end{itemize}

* Volunteering and Extracurricular activities
\begin{itemize}
	\item MSA vice president (2011-2012)
	\item SSA member (2007 – 2012)
\end{itemize}
* References

\begin{itemize}
	\item References are available upon your request.
	\item Email me \href{mailto:eid.alkhaldi@gmail.com}{\email} and I'll refer you to my mentors based on your interests.
\end{itemize}






# Local Variables:
# org-latex-default-packages-alist: nil
# org-latex-packages-alist: nil
# org-latex-with-hyperref: nil
# org-latex-title-command: nil
# org-latex-hyperref-template: nil
# org-export-with-toc: nil
# org-export-with-date: nil
# org-export-with-title: t
# org-latex-title-command: nil
# End:
